modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
[[mods]]
modId="ametropia"
version="${file.jarVersion}"
displayName="Ametropia Limitless"
credits="KUN Dev Lab"
authors="MORIMORI0317"
description='''イキスギた遠視近視MOD'''
